package com.example.createdata.entity;

import java.util.Date;

public class EhrData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.vid
     *
     * @mbggenerated
     */
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.examdate
     *
     * @mbggenerated
     */
    private Date examdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz8
     *
     * @mbggenerated
     */
    private String bz8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz10
     *
     * @mbggenerated
     */
    private String bz10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz11
     *
     * @mbggenerated
     */
    private String bz11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz12
     *
     * @mbggenerated
     */
    private String bz12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz16
     *
     * @mbggenerated
     */
    private String bz16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz17
     *
     * @mbggenerated
     */
    private String bz17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz18
     *
     * @mbggenerated
     */
    private String bz18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz171
     *
     * @mbggenerated
     */
    private String bz171;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz172
     *
     * @mbggenerated
     */
    private String bz172;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz173
     *
     * @mbggenerated
     */
    private String bz173;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz174
     *
     * @mbggenerated
     */
    private String bz174;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz175
     *
     * @mbggenerated
     */
    private String bz175;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz268
     *
     * @mbggenerated
     */
    private String bz268;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz271
     *
     * @mbggenerated
     */
    private String bz271;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz272
     *
     * @mbggenerated
     */
    private String bz272;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz84
     *
     * @mbggenerated
     */
    private String bz84;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz85
     *
     * @mbggenerated
     */
    private String bz85;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz107
     *
     * @mbggenerated
     */
    private String bz107;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz108
     *
     * @mbggenerated
     */
    private String bz108;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz109
     *
     * @mbggenerated
     */
    private String bz109;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz110
     *
     * @mbggenerated
     */
    private String bz110;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz104
     *
     * @mbggenerated
     */
    private String bz104;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz105
     *
     * @mbggenerated
     */
    private String bz105;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz106
     *
     * @mbggenerated
     */
    private String bz106;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz113
     *
     * @mbggenerated
     */
    private String bz113;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz111
     *
     * @mbggenerated
     */
    private String bz111;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz112
     *
     * @mbggenerated
     */
    private String bz112;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz103
     *
     * @mbggenerated
     */
    private String bz103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz120
     *
     * @mbggenerated
     */
    private String bz120;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz119
     *
     * @mbggenerated
     */
    private String bz119;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz121
     *
     * @mbggenerated
     */
    private String bz121;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz81
     *
     * @mbggenerated
     */
    private String bz81;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz82
     *
     * @mbggenerated
     */
    private String bz82;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_data.bz83
     *
     * @mbggenerated
     */
    private String bz83;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.cid
     *
     * @return the value of ehr_data.cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.cid
     *
     * @param cid the value for ehr_data.cid
     *
     * @mbggenerated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.vid
     *
     * @return the value of ehr_data.vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.vid
     *
     * @param vid the value for ehr_data.vid
     *
     * @mbggenerated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.name
     *
     * @return the value of ehr_data.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.name
     *
     * @param name the value for ehr_data.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.gender
     *
     * @return the value of ehr_data.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.gender
     *
     * @param gender the value for ehr_data.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.birthday
     *
     * @return the value of ehr_data.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.birthday
     *
     * @param birthday the value for ehr_data.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.examdate
     *
     * @return the value of ehr_data.examdate
     *
     * @mbggenerated
     */
    public Date getExamdate() {
        return examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.examdate
     *
     * @param examdate the value for ehr_data.examdate
     *
     * @mbggenerated
     */
    public void setExamdate(Date examdate) {
        this.examdate = examdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz8
     *
     * @return the value of ehr_data.bz8
     *
     * @mbggenerated
     */
    public String getBz8() {
        return bz8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz8
     *
     * @param bz8 the value for ehr_data.bz8
     *
     * @mbggenerated
     */
    public void setBz8(String bz8) {
        this.bz8 = bz8 == null ? null : bz8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz10
     *
     * @return the value of ehr_data.bz10
     *
     * @mbggenerated
     */
    public String getBz10() {
        return bz10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz10
     *
     * @param bz10 the value for ehr_data.bz10
     *
     * @mbggenerated
     */
    public void setBz10(String bz10) {
        this.bz10 = bz10 == null ? null : bz10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz11
     *
     * @return the value of ehr_data.bz11
     *
     * @mbggenerated
     */
    public String getBz11() {
        return bz11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz11
     *
     * @param bz11 the value for ehr_data.bz11
     *
     * @mbggenerated
     */
    public void setBz11(String bz11) {
        this.bz11 = bz11 == null ? null : bz11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz12
     *
     * @return the value of ehr_data.bz12
     *
     * @mbggenerated
     */
    public String getBz12() {
        return bz12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz12
     *
     * @param bz12 the value for ehr_data.bz12
     *
     * @mbggenerated
     */
    public void setBz12(String bz12) {
        this.bz12 = bz12 == null ? null : bz12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz16
     *
     * @return the value of ehr_data.bz16
     *
     * @mbggenerated
     */
    public String getBz16() {
        return bz16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz16
     *
     * @param bz16 the value for ehr_data.bz16
     *
     * @mbggenerated
     */
    public void setBz16(String bz16) {
        this.bz16 = bz16 == null ? null : bz16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz17
     *
     * @return the value of ehr_data.bz17
     *
     * @mbggenerated
     */
    public String getBz17() {
        return bz17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz17
     *
     * @param bz17 the value for ehr_data.bz17
     *
     * @mbggenerated
     */
    public void setBz17(String bz17) {
        this.bz17 = bz17 == null ? null : bz17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz18
     *
     * @return the value of ehr_data.bz18
     *
     * @mbggenerated
     */
    public String getBz18() {
        return bz18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz18
     *
     * @param bz18 the value for ehr_data.bz18
     *
     * @mbggenerated
     */
    public void setBz18(String bz18) {
        this.bz18 = bz18 == null ? null : bz18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz171
     *
     * @return the value of ehr_data.bz171
     *
     * @mbggenerated
     */
    public String getBz171() {
        return bz171;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz171
     *
     * @param bz171 the value for ehr_data.bz171
     *
     * @mbggenerated
     */
    public void setBz171(String bz171) {
        this.bz171 = bz171 == null ? null : bz171.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz172
     *
     * @return the value of ehr_data.bz172
     *
     * @mbggenerated
     */
    public String getBz172() {
        return bz172;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz172
     *
     * @param bz172 the value for ehr_data.bz172
     *
     * @mbggenerated
     */
    public void setBz172(String bz172) {
        this.bz172 = bz172 == null ? null : bz172.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz173
     *
     * @return the value of ehr_data.bz173
     *
     * @mbggenerated
     */
    public String getBz173() {
        return bz173;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz173
     *
     * @param bz173 the value for ehr_data.bz173
     *
     * @mbggenerated
     */
    public void setBz173(String bz173) {
        this.bz173 = bz173 == null ? null : bz173.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz174
     *
     * @return the value of ehr_data.bz174
     *
     * @mbggenerated
     */
    public String getBz174() {
        return bz174;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz174
     *
     * @param bz174 the value for ehr_data.bz174
     *
     * @mbggenerated
     */
    public void setBz174(String bz174) {
        this.bz174 = bz174 == null ? null : bz174.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz175
     *
     * @return the value of ehr_data.bz175
     *
     * @mbggenerated
     */
    public String getBz175() {
        return bz175;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz175
     *
     * @param bz175 the value for ehr_data.bz175
     *
     * @mbggenerated
     */
    public void setBz175(String bz175) {
        this.bz175 = bz175 == null ? null : bz175.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz268
     *
     * @return the value of ehr_data.bz268
     *
     * @mbggenerated
     */
    public String getBz268() {
        return bz268;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz268
     *
     * @param bz268 the value for ehr_data.bz268
     *
     * @mbggenerated
     */
    public void setBz268(String bz268) {
        this.bz268 = bz268 == null ? null : bz268.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz271
     *
     * @return the value of ehr_data.bz271
     *
     * @mbggenerated
     */
    public String getBz271() {
        return bz271;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz271
     *
     * @param bz271 the value for ehr_data.bz271
     *
     * @mbggenerated
     */
    public void setBz271(String bz271) {
        this.bz271 = bz271 == null ? null : bz271.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz272
     *
     * @return the value of ehr_data.bz272
     *
     * @mbggenerated
     */
    public String getBz272() {
        return bz272;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz272
     *
     * @param bz272 the value for ehr_data.bz272
     *
     * @mbggenerated
     */
    public void setBz272(String bz272) {
        this.bz272 = bz272 == null ? null : bz272.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz84
     *
     * @return the value of ehr_data.bz84
     *
     * @mbggenerated
     */
    public String getBz84() {
        return bz84;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz84
     *
     * @param bz84 the value for ehr_data.bz84
     *
     * @mbggenerated
     */
    public void setBz84(String bz84) {
        this.bz84 = bz84 == null ? null : bz84.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz85
     *
     * @return the value of ehr_data.bz85
     *
     * @mbggenerated
     */
    public String getBz85() {
        return bz85;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz85
     *
     * @param bz85 the value for ehr_data.bz85
     *
     * @mbggenerated
     */
    public void setBz85(String bz85) {
        this.bz85 = bz85 == null ? null : bz85.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz107
     *
     * @return the value of ehr_data.bz107
     *
     * @mbggenerated
     */
    public String getBz107() {
        return bz107;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz107
     *
     * @param bz107 the value for ehr_data.bz107
     *
     * @mbggenerated
     */
    public void setBz107(String bz107) {
        this.bz107 = bz107 == null ? null : bz107.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz108
     *
     * @return the value of ehr_data.bz108
     *
     * @mbggenerated
     */
    public String getBz108() {
        return bz108;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz108
     *
     * @param bz108 the value for ehr_data.bz108
     *
     * @mbggenerated
     */
    public void setBz108(String bz108) {
        this.bz108 = bz108 == null ? null : bz108.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz109
     *
     * @return the value of ehr_data.bz109
     *
     * @mbggenerated
     */
    public String getBz109() {
        return bz109;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz109
     *
     * @param bz109 the value for ehr_data.bz109
     *
     * @mbggenerated
     */
    public void setBz109(String bz109) {
        this.bz109 = bz109 == null ? null : bz109.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz110
     *
     * @return the value of ehr_data.bz110
     *
     * @mbggenerated
     */
    public String getBz110() {
        return bz110;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz110
     *
     * @param bz110 the value for ehr_data.bz110
     *
     * @mbggenerated
     */
    public void setBz110(String bz110) {
        this.bz110 = bz110 == null ? null : bz110.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz104
     *
     * @return the value of ehr_data.bz104
     *
     * @mbggenerated
     */
    public String getBz104() {
        return bz104;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz104
     *
     * @param bz104 the value for ehr_data.bz104
     *
     * @mbggenerated
     */
    public void setBz104(String bz104) {
        this.bz104 = bz104 == null ? null : bz104.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz105
     *
     * @return the value of ehr_data.bz105
     *
     * @mbggenerated
     */
    public String getBz105() {
        return bz105;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz105
     *
     * @param bz105 the value for ehr_data.bz105
     *
     * @mbggenerated
     */
    public void setBz105(String bz105) {
        this.bz105 = bz105 == null ? null : bz105.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz106
     *
     * @return the value of ehr_data.bz106
     *
     * @mbggenerated
     */
    public String getBz106() {
        return bz106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz106
     *
     * @param bz106 the value for ehr_data.bz106
     *
     * @mbggenerated
     */
    public void setBz106(String bz106) {
        this.bz106 = bz106 == null ? null : bz106.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz113
     *
     * @return the value of ehr_data.bz113
     *
     * @mbggenerated
     */
    public String getBz113() {
        return bz113;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz113
     *
     * @param bz113 the value for ehr_data.bz113
     *
     * @mbggenerated
     */
    public void setBz113(String bz113) {
        this.bz113 = bz113 == null ? null : bz113.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz111
     *
     * @return the value of ehr_data.bz111
     *
     * @mbggenerated
     */
    public String getBz111() {
        return bz111;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz111
     *
     * @param bz111 the value for ehr_data.bz111
     *
     * @mbggenerated
     */
    public void setBz111(String bz111) {
        this.bz111 = bz111 == null ? null : bz111.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz112
     *
     * @return the value of ehr_data.bz112
     *
     * @mbggenerated
     */
    public String getBz112() {
        return bz112;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz112
     *
     * @param bz112 the value for ehr_data.bz112
     *
     * @mbggenerated
     */
    public void setBz112(String bz112) {
        this.bz112 = bz112 == null ? null : bz112.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz103
     *
     * @return the value of ehr_data.bz103
     *
     * @mbggenerated
     */
    public String getBz103() {
        return bz103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz103
     *
     * @param bz103 the value for ehr_data.bz103
     *
     * @mbggenerated
     */
    public void setBz103(String bz103) {
        this.bz103 = bz103 == null ? null : bz103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz120
     *
     * @return the value of ehr_data.bz120
     *
     * @mbggenerated
     */
    public String getBz120() {
        return bz120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz120
     *
     * @param bz120 the value for ehr_data.bz120
     *
     * @mbggenerated
     */
    public void setBz120(String bz120) {
        this.bz120 = bz120 == null ? null : bz120.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz119
     *
     * @return the value of ehr_data.bz119
     *
     * @mbggenerated
     */
    public String getBz119() {
        return bz119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz119
     *
     * @param bz119 the value for ehr_data.bz119
     *
     * @mbggenerated
     */
    public void setBz119(String bz119) {
        this.bz119 = bz119 == null ? null : bz119.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz121
     *
     * @return the value of ehr_data.bz121
     *
     * @mbggenerated
     */
    public String getBz121() {
        return bz121;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz121
     *
     * @param bz121 the value for ehr_data.bz121
     *
     * @mbggenerated
     */
    public void setBz121(String bz121) {
        this.bz121 = bz121 == null ? null : bz121.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz81
     *
     * @return the value of ehr_data.bz81
     *
     * @mbggenerated
     */
    public String getBz81() {
        return bz81;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz81
     *
     * @param bz81 the value for ehr_data.bz81
     *
     * @mbggenerated
     */
    public void setBz81(String bz81) {
        this.bz81 = bz81 == null ? null : bz81.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz82
     *
     * @return the value of ehr_data.bz82
     *
     * @mbggenerated
     */
    public String getBz82() {
        return bz82;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz82
     *
     * @param bz82 the value for ehr_data.bz82
     *
     * @mbggenerated
     */
    public void setBz82(String bz82) {
        this.bz82 = bz82 == null ? null : bz82.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_data.bz83
     *
     * @return the value of ehr_data.bz83
     *
     * @mbggenerated
     */
    public String getBz83() {
        return bz83;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_data.bz83
     *
     * @param bz83 the value for ehr_data.bz83
     *
     * @mbggenerated
     */
    public void setBz83(String bz83) {
        this.bz83 = bz83 == null ? null : bz83.trim();
    }
}