package com.example.demo.entity;

import com.sun.javafx.beans.IDProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;
@Data
@AllArgsConstructor
@NoArgsConstructor
@Accessors(chain = true)
@Entity(name="ehr")
public class Ehr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Vid
     *
     * @mbggenerated
     */
    @Id
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Xm
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Xb
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Csrq
     *
     * @mbggenerated
     */
    private Date csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Yysj
     *
     * @mbggenerated
     */
    private Date yysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Mz
     *
     * @mbggenerated
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz1
     *
     * @mbggenerated
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz2
     *
     * @mbggenerated
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz3
     *
     * @mbggenerated
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz4
     *
     * @mbggenerated
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz5
     *
     * @mbggenerated
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz6
     *
     * @mbggenerated
     */
    private String bz6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz7
     *
     * @mbggenerated
     */
    private String bz7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz8
     *
     * @mbggenerated
     */
    private String bz8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz9
     *
     * @mbggenerated
     */
    private String bz9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz10
     *
     * @mbggenerated
     */
    private String bz10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz11
     *
     * @mbggenerated
     */
    private String bz11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz12
     *
     * @mbggenerated
     */
    private String bz12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz13
     *
     * @mbggenerated
     */
    private String bz13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz14
     *
     * @mbggenerated
     */
    private String bz14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz15
     *
     * @mbggenerated
     */
    private String bz15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz139
     *
     * @mbggenerated
     */
    private String bz139;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz131
     *
     * @mbggenerated
     */
    private String bz131;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz149
     *
     * @mbggenerated
     */
    private String bz149;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz135
     *
     * @mbggenerated
     */
    private String bz135;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz141
     *
     * @mbggenerated
     */
    private String bz141;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz137
     *
     * @mbggenerated
     */
    private String bz137;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz147
     *
     * @mbggenerated
     */
    private String bz147;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz145
     *
     * @mbggenerated
     */
    private String bz145;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz143
     *
     * @mbggenerated
     */
    private String bz143;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz204
     *
     * @mbggenerated
     */
    private String bz204;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz205
     *
     * @mbggenerated
     */
    private String bz205;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz206
     *
     * @mbggenerated
     */
    private String bz206;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz152
     *
     * @mbggenerated
     */
    private String bz152;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz153
     *
     * @mbggenerated
     */
    private String bz153;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz155
     *
     * @mbggenerated
     */
    private String bz155;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz157
     *
     * @mbggenerated
     */
    private String bz157;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz160
     *
     * @mbggenerated
     */
    private String bz160;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz158
     *
     * @mbggenerated
     */
    private String bz158;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz159
     *
     * @mbggenerated
     */
    private String bz159;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz102
     *
     * @mbggenerated
     */
    private String bz102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz154
     *
     * @mbggenerated
     */
    private String bz154;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz130
     *
     * @mbggenerated
     */
    private String bz130;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz151
     *
     * @mbggenerated
     */
    private String bz151;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz144
     *
     * @mbggenerated
     */
    private String bz144;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz134
     *
     * @mbggenerated
     */
    private String bz134;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz142
     *
     * @mbggenerated
     */
    private String bz142;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz132
     *
     * @mbggenerated
     */
    private String bz132;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz162
     *
     * @mbggenerated
     */
    private String bz162;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz163
     *
     * @mbggenerated
     */
    private String bz163;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz165
     *
     * @mbggenerated
     */
    private String bz165;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz146
     *
     * @mbggenerated
     */
    private String bz146;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz136
     *
     * @mbggenerated
     */
    private String bz136;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz115
     *
     * @mbggenerated
     */
    private String bz115;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz116
     *
     * @mbggenerated
     */
    private String bz116;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz117
     *
     * @mbggenerated
     */
    private String bz117;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz118
     *
     * @mbggenerated
     */
    private String bz118;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.Bz128
     *
     * @mbggenerated
     */
    private String bz128;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Vid
     *
     * @return the value of ehr.Vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Vid
     *
     * @param vid the value for ehr.Vid
     *
     * @mbggenerated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Cid
     *
     * @return the value of ehr.Cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Cid
     *
     * @param cid the value for ehr.Cid
     *
     * @mbggenerated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Xm
     *
     * @return the value of ehr.Xm
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Xm
     *
     * @param xm the value for ehr.Xm
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Xb
     *
     * @return the value of ehr.Xb
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Xb
     *
     * @param xb the value for ehr.Xb
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Csrq
     *
     * @return the value of ehr.Csrq
     *
     * @mbggenerated
     */
    public Date getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Csrq
     *
     * @param csrq the value for ehr.Csrq
     *
     * @mbggenerated
     */
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Yysj
     *
     * @return the value of ehr.Yysj
     *
     * @mbggenerated
     */
    public Date getYysj() {
        return yysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Yysj
     *
     * @param yysj the value for ehr.Yysj
     *
     * @mbggenerated
     */
    public void setYysj(Date yysj) {
        this.yysj = yysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Mz
     *
     * @return the value of ehr.Mz
     *
     * @mbggenerated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Mz
     *
     * @param mz the value for ehr.Mz
     *
     * @mbggenerated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz1
     *
     * @return the value of ehr.Bz1
     *
     * @mbggenerated
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz1
     *
     * @param bz1 the value for ehr.Bz1
     *
     * @mbggenerated
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1 == null ? null : bz1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz2
     *
     * @return the value of ehr.Bz2
     *
     * @mbggenerated
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz2
     *
     * @param bz2 the value for ehr.Bz2
     *
     * @mbggenerated
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2 == null ? null : bz2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz3
     *
     * @return the value of ehr.Bz3
     *
     * @mbggenerated
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz3
     *
     * @param bz3 the value for ehr.Bz3
     *
     * @mbggenerated
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3 == null ? null : bz3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz4
     *
     * @return the value of ehr.Bz4
     *
     * @mbggenerated
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz4
     *
     * @param bz4 the value for ehr.Bz4
     *
     * @mbggenerated
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4 == null ? null : bz4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz5
     *
     * @return the value of ehr.Bz5
     *
     * @mbggenerated
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz5
     *
     * @param bz5 the value for ehr.Bz5
     *
     * @mbggenerated
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5 == null ? null : bz5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz6
     *
     * @return the value of ehr.Bz6
     *
     * @mbggenerated
     */
    public String getBz6() {
        return bz6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz6
     *
     * @param bz6 the value for ehr.Bz6
     *
     * @mbggenerated
     */
    public void setBz6(String bz6) {
        this.bz6 = bz6 == null ? null : bz6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz7
     *
     * @return the value of ehr.Bz7
     *
     * @mbggenerated
     */
    public String getBz7() {
        return bz7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz7
     *
     * @param bz7 the value for ehr.Bz7
     *
     * @mbggenerated
     */
    public void setBz7(String bz7) {
        this.bz7 = bz7 == null ? null : bz7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz8
     *
     * @return the value of ehr.Bz8
     *
     * @mbggenerated
     */
    public String getBz8() {
        return bz8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz8
     *
     * @param bz8 the value for ehr.Bz8
     *
     * @mbggenerated
     */
    public void setBz8(String bz8) {
        this.bz8 = bz8 == null ? null : bz8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz9
     *
     * @return the value of ehr.Bz9
     *
     * @mbggenerated
     */
    public String getBz9() {
        return bz9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz9
     *
     * @param bz9 the value for ehr.Bz9
     *
     * @mbggenerated
     */
    public void setBz9(String bz9) {
        this.bz9 = bz9 == null ? null : bz9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz10
     *
     * @return the value of ehr.Bz10
     *
     * @mbggenerated
     */
    public String getBz10() {
        return bz10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz10
     *
     * @param bz10 the value for ehr.Bz10
     *
     * @mbggenerated
     */
    public void setBz10(String bz10) {
        this.bz10 = bz10 == null ? null : bz10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz11
     *
     * @return the value of ehr.Bz11
     *
     * @mbggenerated
     */
    public String getBz11() {
        return bz11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz11
     *
     * @param bz11 the value for ehr.Bz11
     *
     * @mbggenerated
     */
    public void setBz11(String bz11) {
        this.bz11 = bz11 == null ? null : bz11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz12
     *
     * @return the value of ehr.Bz12
     *
     * @mbggenerated
     */
    public String getBz12() {
        return bz12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz12
     *
     * @param bz12 the value for ehr.Bz12
     *
     * @mbggenerated
     */
    public void setBz12(String bz12) {
        this.bz12 = bz12 == null ? null : bz12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz13
     *
     * @return the value of ehr.Bz13
     *
     * @mbggenerated
     */
    public String getBz13() {
        return bz13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz13
     *
     * @param bz13 the value for ehr.Bz13
     *
     * @mbggenerated
     */
    public void setBz13(String bz13) {
        this.bz13 = bz13 == null ? null : bz13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz14
     *
     * @return the value of ehr.Bz14
     *
     * @mbggenerated
     */
    public String getBz14() {
        return bz14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz14
     *
     * @param bz14 the value for ehr.Bz14
     *
     * @mbggenerated
     */
    public void setBz14(String bz14) {
        this.bz14 = bz14 == null ? null : bz14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz15
     *
     * @return the value of ehr.Bz15
     *
     * @mbggenerated
     */
    public String getBz15() {
        return bz15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz15
     *
     * @param bz15 the value for ehr.Bz15
     *
     * @mbggenerated
     */
    public void setBz15(String bz15) {
        this.bz15 = bz15 == null ? null : bz15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz139
     *
     * @return the value of ehr.Bz139
     *
     * @mbggenerated
     */
    public String getBz139() {
        return bz139;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz139
     *
     * @param bz139 the value for ehr.Bz139
     *
     * @mbggenerated
     */
    public void setBz139(String bz139) {
        this.bz139 = bz139 == null ? null : bz139.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz131
     *
     * @return the value of ehr.Bz131
     *
     * @mbggenerated
     */
    public String getBz131() {
        return bz131;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz131
     *
     * @param bz131 the value for ehr.Bz131
     *
     * @mbggenerated
     */
    public void setBz131(String bz131) {
        this.bz131 = bz131 == null ? null : bz131.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz149
     *
     * @return the value of ehr.Bz149
     *
     * @mbggenerated
     */
    public String getBz149() {
        return bz149;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz149
     *
     * @param bz149 the value for ehr.Bz149
     *
     * @mbggenerated
     */
    public void setBz149(String bz149) {
        this.bz149 = bz149 == null ? null : bz149.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz135
     *
     * @return the value of ehr.Bz135
     *
     * @mbggenerated
     */
    public String getBz135() {
        return bz135;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz135
     *
     * @param bz135 the value for ehr.Bz135
     *
     * @mbggenerated
     */
    public void setBz135(String bz135) {
        this.bz135 = bz135 == null ? null : bz135.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz141
     *
     * @return the value of ehr.Bz141
     *
     * @mbggenerated
     */
    public String getBz141() {
        return bz141;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz141
     *
     * @param bz141 the value for ehr.Bz141
     *
     * @mbggenerated
     */
    public void setBz141(String bz141) {
        this.bz141 = bz141 == null ? null : bz141.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz137
     *
     * @return the value of ehr.Bz137
     *
     * @mbggenerated
     */
    public String getBz137() {
        return bz137;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz137
     *
     * @param bz137 the value for ehr.Bz137
     *
     * @mbggenerated
     */
    public void setBz137(String bz137) {
        this.bz137 = bz137 == null ? null : bz137.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz147
     *
     * @return the value of ehr.Bz147
     *
     * @mbggenerated
     */
    public String getBz147() {
        return bz147;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz147
     *
     * @param bz147 the value for ehr.Bz147
     *
     * @mbggenerated
     */
    public void setBz147(String bz147) {
        this.bz147 = bz147 == null ? null : bz147.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz145
     *
     * @return the value of ehr.Bz145
     *
     * @mbggenerated
     */
    public String getBz145() {
        return bz145;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz145
     *
     * @param bz145 the value for ehr.Bz145
     *
     * @mbggenerated
     */
    public void setBz145(String bz145) {
        this.bz145 = bz145 == null ? null : bz145.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz143
     *
     * @return the value of ehr.Bz143
     *
     * @mbggenerated
     */
    public String getBz143() {
        return bz143;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz143
     *
     * @param bz143 the value for ehr.Bz143
     *
     * @mbggenerated
     */
    public void setBz143(String bz143) {
        this.bz143 = bz143 == null ? null : bz143.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz204
     *
     * @return the value of ehr.Bz204
     *
     * @mbggenerated
     */
    public String getBz204() {
        return bz204;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz204
     *
     * @param bz204 the value for ehr.Bz204
     *
     * @mbggenerated
     */
    public void setBz204(String bz204) {
        this.bz204 = bz204 == null ? null : bz204.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz205
     *
     * @return the value of ehr.Bz205
     *
     * @mbggenerated
     */
    public String getBz205() {
        return bz205;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz205
     *
     * @param bz205 the value for ehr.Bz205
     *
     * @mbggenerated
     */
    public void setBz205(String bz205) {
        this.bz205 = bz205 == null ? null : bz205.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz206
     *
     * @return the value of ehr.Bz206
     *
     * @mbggenerated
     */
    public String getBz206() {
        return bz206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz206
     *
     * @param bz206 the value for ehr.Bz206
     *
     * @mbggenerated
     */
    public void setBz206(String bz206) {
        this.bz206 = bz206 == null ? null : bz206.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz152
     *
     * @return the value of ehr.Bz152
     *
     * @mbggenerated
     */
    public String getBz152() {
        return bz152;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz152
     *
     * @param bz152 the value for ehr.Bz152
     *
     * @mbggenerated
     */
    public void setBz152(String bz152) {
        this.bz152 = bz152 == null ? null : bz152.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz153
     *
     * @return the value of ehr.Bz153
     *
     * @mbggenerated
     */
    public String getBz153() {
        return bz153;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz153
     *
     * @param bz153 the value for ehr.Bz153
     *
     * @mbggenerated
     */
    public void setBz153(String bz153) {
        this.bz153 = bz153 == null ? null : bz153.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz155
     *
     * @return the value of ehr.Bz155
     *
     * @mbggenerated
     */
    public String getBz155() {
        return bz155;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz155
     *
     * @param bz155 the value for ehr.Bz155
     *
     * @mbggenerated
     */
    public void setBz155(String bz155) {
        this.bz155 = bz155 == null ? null : bz155.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz157
     *
     * @return the value of ehr.Bz157
     *
     * @mbggenerated
     */
    public String getBz157() {
        return bz157;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz157
     *
     * @param bz157 the value for ehr.Bz157
     *
     * @mbggenerated
     */
    public void setBz157(String bz157) {
        this.bz157 = bz157 == null ? null : bz157.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz160
     *
     * @return the value of ehr.Bz160
     *
     * @mbggenerated
     */
    public String getBz160() {
        return bz160;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz160
     *
     * @param bz160 the value for ehr.Bz160
     *
     * @mbggenerated
     */
    public void setBz160(String bz160) {
        this.bz160 = bz160 == null ? null : bz160.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz158
     *
     * @return the value of ehr.Bz158
     *
     * @mbggenerated
     */
    public String getBz158() {
        return bz158;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz158
     *
     * @param bz158 the value for ehr.Bz158
     *
     * @mbggenerated
     */
    public void setBz158(String bz158) {
        this.bz158 = bz158 == null ? null : bz158.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz159
     *
     * @return the value of ehr.Bz159
     *
     * @mbggenerated
     */
    public String getBz159() {
        return bz159;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz159
     *
     * @param bz159 the value for ehr.Bz159
     *
     * @mbggenerated
     */
    public void setBz159(String bz159) {
        this.bz159 = bz159 == null ? null : bz159.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz102
     *
     * @return the value of ehr.Bz102
     *
     * @mbggenerated
     */
    public String getBz102() {
        return bz102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz102
     *
     * @param bz102 the value for ehr.Bz102
     *
     * @mbggenerated
     */
    public void setBz102(String bz102) {
        this.bz102 = bz102 == null ? null : bz102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz154
     *
     * @return the value of ehr.Bz154
     *
     * @mbggenerated
     */
    public String getBz154() {
        return bz154;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz154
     *
     * @param bz154 the value for ehr.Bz154
     *
     * @mbggenerated
     */
    public void setBz154(String bz154) {
        this.bz154 = bz154 == null ? null : bz154.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz130
     *
     * @return the value of ehr.Bz130
     *
     * @mbggenerated
     */
    public String getBz130() {
        return bz130;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz130
     *
     * @param bz130 the value for ehr.Bz130
     *
     * @mbggenerated
     */
    public void setBz130(String bz130) {
        this.bz130 = bz130 == null ? null : bz130.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz151
     *
     * @return the value of ehr.Bz151
     *
     * @mbggenerated
     */
    public String getBz151() {
        return bz151;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz151
     *
     * @param bz151 the value for ehr.Bz151
     *
     * @mbggenerated
     */
    public void setBz151(String bz151) {
        this.bz151 = bz151 == null ? null : bz151.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz144
     *
     * @return the value of ehr.Bz144
     *
     * @mbggenerated
     */
    public String getBz144() {
        return bz144;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz144
     *
     * @param bz144 the value for ehr.Bz144
     *
     * @mbggenerated
     */
    public void setBz144(String bz144) {
        this.bz144 = bz144 == null ? null : bz144.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz134
     *
     * @return the value of ehr.Bz134
     *
     * @mbggenerated
     */
    public String getBz134() {
        return bz134;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz134
     *
     * @param bz134 the value for ehr.Bz134
     *
     * @mbggenerated
     */
    public void setBz134(String bz134) {
        this.bz134 = bz134 == null ? null : bz134.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz142
     *
     * @return the value of ehr.Bz142
     *
     * @mbggenerated
     */
    public String getBz142() {
        return bz142;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz142
     *
     * @param bz142 the value for ehr.Bz142
     *
     * @mbggenerated
     */
    public void setBz142(String bz142) {
        this.bz142 = bz142 == null ? null : bz142.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz132
     *
     * @return the value of ehr.Bz132
     *
     * @mbggenerated
     */
    public String getBz132() {
        return bz132;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz132
     *
     * @param bz132 the value for ehr.Bz132
     *
     * @mbggenerated
     */
    public void setBz132(String bz132) {
        this.bz132 = bz132 == null ? null : bz132.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz162
     *
     * @return the value of ehr.Bz162
     *
     * @mbggenerated
     */
    public String getBz162() {
        return bz162;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz162
     *
     * @param bz162 the value for ehr.Bz162
     *
     * @mbggenerated
     */
    public void setBz162(String bz162) {
        this.bz162 = bz162 == null ? null : bz162.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz163
     *
     * @return the value of ehr.Bz163
     *
     * @mbggenerated
     */
    public String getBz163() {
        return bz163;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz163
     *
     * @param bz163 the value for ehr.Bz163
     *
     * @mbggenerated
     */
    public void setBz163(String bz163) {
        this.bz163 = bz163 == null ? null : bz163.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz165
     *
     * @return the value of ehr.Bz165
     *
     * @mbggenerated
     */
    public String getBz165() {
        return bz165;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz165
     *
     * @param bz165 the value for ehr.Bz165
     *
     * @mbggenerated
     */
    public void setBz165(String bz165) {
        this.bz165 = bz165 == null ? null : bz165.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz146
     *
     * @return the value of ehr.Bz146
     *
     * @mbggenerated
     */
    public String getBz146() {
        return bz146;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz146
     *
     * @param bz146 the value for ehr.Bz146
     *
     * @mbggenerated
     */
    public void setBz146(String bz146) {
        this.bz146 = bz146 == null ? null : bz146.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz136
     *
     * @return the value of ehr.Bz136
     *
     * @mbggenerated
     */
    public String getBz136() {
        return bz136;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz136
     *
     * @param bz136 the value for ehr.Bz136
     *
     * @mbggenerated
     */
    public void setBz136(String bz136) {
        this.bz136 = bz136 == null ? null : bz136.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz115
     *
     * @return the value of ehr.Bz115
     *
     * @mbggenerated
     */
    public String getBz115() {
        return bz115;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz115
     *
     * @param bz115 the value for ehr.Bz115
     *
     * @mbggenerated
     */
    public void setBz115(String bz115) {
        this.bz115 = bz115 == null ? null : bz115.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz116
     *
     * @return the value of ehr.Bz116
     *
     * @mbggenerated
     */
    public String getBz116() {
        return bz116;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz116
     *
     * @param bz116 the value for ehr.Bz116
     *
     * @mbggenerated
     */
    public void setBz116(String bz116) {
        this.bz116 = bz116 == null ? null : bz116.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz117
     *
     * @return the value of ehr.Bz117
     *
     * @mbggenerated
     */
    public String getBz117() {
        return bz117;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz117
     *
     * @param bz117 the value for ehr.Bz117
     *
     * @mbggenerated
     */
    public void setBz117(String bz117) {
        this.bz117 = bz117 == null ? null : bz117.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz118
     *
     * @return the value of ehr.Bz118
     *
     * @mbggenerated
     */
    public String getBz118() {
        return bz118;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz118
     *
     * @param bz118 the value for ehr.Bz118
     *
     * @mbggenerated
     */
    public void setBz118(String bz118) {
        this.bz118 = bz118 == null ? null : bz118.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.Bz128
     *
     * @return the value of ehr.Bz128
     *
     * @mbggenerated
     */
    public String getBz128() {
        return bz128;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.Bz128
     *
     * @param bz128 the value for ehr.Bz128
     *
     * @mbggenerated
     */
    public void setBz128(String bz128) {
        this.bz128 = bz128 == null ? null : bz128.trim();
    }
}