package com.example.demo.entity;

import java.util.Date;

public class Ehr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.vid
     *
     * @mbggenerated
     */
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.xm
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.xb
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.csrq
     *
     * @mbggenerated
     */
    private Date csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.yysj
     *
     * @mbggenerated
     */
    private Date yysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.mz
     *
     * @mbggenerated
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz1
     *
     * @mbggenerated
     */
    private String bz1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz2
     *
     * @mbggenerated
     */
    private String bz2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz3
     *
     * @mbggenerated
     */
    private String bz3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz4
     *
     * @mbggenerated
     */
    private String bz4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz5
     *
     * @mbggenerated
     */
    private String bz5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz6
     *
     * @mbggenerated
     */
    private String bz6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz7
     *
     * @mbggenerated
     */
    private String bz7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz8
     *
     * @mbggenerated
     */
    private String bz8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz9
     *
     * @mbggenerated
     */
    private String bz9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz10
     *
     * @mbggenerated
     */
    private String bz10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz11
     *
     * @mbggenerated
     */
    private String bz11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz12
     *
     * @mbggenerated
     */
    private String bz12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz13
     *
     * @mbggenerated
     */
    private String bz13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz14
     *
     * @mbggenerated
     */
    private String bz14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz15
     *
     * @mbggenerated
     */
    private String bz15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz16
     *
     * @mbggenerated
     */
    private String bz16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz17
     *
     * @mbggenerated
     */
    private String bz17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz18
     *
     * @mbggenerated
     */
    private String bz18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz81
     *
     * @mbggenerated
     */
    private String bz81;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz82
     *
     * @mbggenerated
     */
    private String bz82;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz83
     *
     * @mbggenerated
     */
    private String bz83;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz84
     *
     * @mbggenerated
     */
    private String bz84;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz85
     *
     * @mbggenerated
     */
    private String bz85;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz102
     *
     * @mbggenerated
     */
    private String bz102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz103
     *
     * @mbggenerated
     */
    private String bz103;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz104
     *
     * @mbggenerated
     */
    private String bz104;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz105
     *
     * @mbggenerated
     */
    private String bz105;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz106
     *
     * @mbggenerated
     */
    private String bz106;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz107
     *
     * @mbggenerated
     */
    private String bz107;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz108
     *
     * @mbggenerated
     */
    private String bz108;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz109
     *
     * @mbggenerated
     */
    private String bz109;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz110
     *
     * @mbggenerated
     */
    private String bz110;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz111
     *
     * @mbggenerated
     */
    private String bz111;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz112
     *
     * @mbggenerated
     */
    private String bz112;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz113
     *
     * @mbggenerated
     */
    private String bz113;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz115
     *
     * @mbggenerated
     */
    private String bz115;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz116
     *
     * @mbggenerated
     */
    private String bz116;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz117
     *
     * @mbggenerated
     */
    private String bz117;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz118
     *
     * @mbggenerated
     */
    private String bz118;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz119
     *
     * @mbggenerated
     */
    private String bz119;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz120
     *
     * @mbggenerated
     */
    private String bz120;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz121
     *
     * @mbggenerated
     */
    private String bz121;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz128
     *
     * @mbggenerated
     */
    private String bz128;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz130
     *
     * @mbggenerated
     */
    private String bz130;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz131
     *
     * @mbggenerated
     */
    private String bz131;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz132
     *
     * @mbggenerated
     */
    private String bz132;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz134
     *
     * @mbggenerated
     */
    private String bz134;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz135
     *
     * @mbggenerated
     */
    private String bz135;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz136
     *
     * @mbggenerated
     */
    private String bz136;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz137
     *
     * @mbggenerated
     */
    private String bz137;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz139
     *
     * @mbggenerated
     */
    private String bz139;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz141
     *
     * @mbggenerated
     */
    private String bz141;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz142
     *
     * @mbggenerated
     */
    private String bz142;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz143
     *
     * @mbggenerated
     */
    private String bz143;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz144
     *
     * @mbggenerated
     */
    private String bz144;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz145
     *
     * @mbggenerated
     */
    private String bz145;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz146
     *
     * @mbggenerated
     */
    private String bz146;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz147
     *
     * @mbggenerated
     */
    private String bz147;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz149
     *
     * @mbggenerated
     */
    private String bz149;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz151
     *
     * @mbggenerated
     */
    private String bz151;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz152
     *
     * @mbggenerated
     */
    private String bz152;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz153
     *
     * @mbggenerated
     */
    private String bz153;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz154
     *
     * @mbggenerated
     */
    private String bz154;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz155
     *
     * @mbggenerated
     */
    private String bz155;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz157
     *
     * @mbggenerated
     */
    private String bz157;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz158
     *
     * @mbggenerated
     */
    private String bz158;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz159
     *
     * @mbggenerated
     */
    private String bz159;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz160
     *
     * @mbggenerated
     */
    private String bz160;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz162
     *
     * @mbggenerated
     */
    private String bz162;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz163
     *
     * @mbggenerated
     */
    private String bz163;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz165
     *
     * @mbggenerated
     */
    private String bz165;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz171
     *
     * @mbggenerated
     */
    private String bz171;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz172
     *
     * @mbggenerated
     */
    private String bz172;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz173
     *
     * @mbggenerated
     */
    private String bz173;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz174
     *
     * @mbggenerated
     */
    private String bz174;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz175
     *
     * @mbggenerated
     */
    private String bz175;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz204
     *
     * @mbggenerated
     */
    private String bz204;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz205
     *
     * @mbggenerated
     */
    private String bz205;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz206
     *
     * @mbggenerated
     */
    private String bz206;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz268
     *
     * @mbggenerated
     */
    private String bz268;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz271
     *
     * @mbggenerated
     */
    private String bz271;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr.bz272
     *
     * @mbggenerated
     */
    private String bz272;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.vid
     *
     * @return the value of ehr.vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.vid
     *
     * @param vid the value for ehr.vid
     *
     * @mbggenerated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.cid
     *
     * @return the value of ehr.cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.cid
     *
     * @param cid the value for ehr.cid
     *
     * @mbggenerated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.xm
     *
     * @return the value of ehr.xm
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.xm
     *
     * @param xm the value for ehr.xm
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.xb
     *
     * @return the value of ehr.xb
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.xb
     *
     * @param xb the value for ehr.xb
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.csrq
     *
     * @return the value of ehr.csrq
     *
     * @mbggenerated
     */
    public Date getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.csrq
     *
     * @param csrq the value for ehr.csrq
     *
     * @mbggenerated
     */
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.yysj
     *
     * @return the value of ehr.yysj
     *
     * @mbggenerated
     */
    public Date getYysj() {
        return yysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.yysj
     *
     * @param yysj the value for ehr.yysj
     *
     * @mbggenerated
     */
    public void setYysj(Date yysj) {
        this.yysj = yysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.mz
     *
     * @return the value of ehr.mz
     *
     * @mbggenerated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.mz
     *
     * @param mz the value for ehr.mz
     *
     * @mbggenerated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz1
     *
     * @return the value of ehr.bz1
     *
     * @mbggenerated
     */
    public String getBz1() {
        return bz1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz1
     *
     * @param bz1 the value for ehr.bz1
     *
     * @mbggenerated
     */
    public void setBz1(String bz1) {
        this.bz1 = bz1 == null ? null : bz1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz2
     *
     * @return the value of ehr.bz2
     *
     * @mbggenerated
     */
    public String getBz2() {
        return bz2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz2
     *
     * @param bz2 the value for ehr.bz2
     *
     * @mbggenerated
     */
    public void setBz2(String bz2) {
        this.bz2 = bz2 == null ? null : bz2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz3
     *
     * @return the value of ehr.bz3
     *
     * @mbggenerated
     */
    public String getBz3() {
        return bz3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz3
     *
     * @param bz3 the value for ehr.bz3
     *
     * @mbggenerated
     */
    public void setBz3(String bz3) {
        this.bz3 = bz3 == null ? null : bz3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz4
     *
     * @return the value of ehr.bz4
     *
     * @mbggenerated
     */
    public String getBz4() {
        return bz4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz4
     *
     * @param bz4 the value for ehr.bz4
     *
     * @mbggenerated
     */
    public void setBz4(String bz4) {
        this.bz4 = bz4 == null ? null : bz4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz5
     *
     * @return the value of ehr.bz5
     *
     * @mbggenerated
     */
    public String getBz5() {
        return bz5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz5
     *
     * @param bz5 the value for ehr.bz5
     *
     * @mbggenerated
     */
    public void setBz5(String bz5) {
        this.bz5 = bz5 == null ? null : bz5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz6
     *
     * @return the value of ehr.bz6
     *
     * @mbggenerated
     */
    public String getBz6() {
        return bz6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz6
     *
     * @param bz6 the value for ehr.bz6
     *
     * @mbggenerated
     */
    public void setBz6(String bz6) {
        this.bz6 = bz6 == null ? null : bz6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz7
     *
     * @return the value of ehr.bz7
     *
     * @mbggenerated
     */
    public String getBz7() {
        return bz7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz7
     *
     * @param bz7 the value for ehr.bz7
     *
     * @mbggenerated
     */
    public void setBz7(String bz7) {
        this.bz7 = bz7 == null ? null : bz7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz8
     *
     * @return the value of ehr.bz8
     *
     * @mbggenerated
     */
    public String getBz8() {
        return bz8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz8
     *
     * @param bz8 the value for ehr.bz8
     *
     * @mbggenerated
     */
    public void setBz8(String bz8) {
        this.bz8 = bz8 == null ? null : bz8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz9
     *
     * @return the value of ehr.bz9
     *
     * @mbggenerated
     */
    public String getBz9() {
        return bz9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz9
     *
     * @param bz9 the value for ehr.bz9
     *
     * @mbggenerated
     */
    public void setBz9(String bz9) {
        this.bz9 = bz9 == null ? null : bz9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz10
     *
     * @return the value of ehr.bz10
     *
     * @mbggenerated
     */
    public String getBz10() {
        return bz10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz10
     *
     * @param bz10 the value for ehr.bz10
     *
     * @mbggenerated
     */
    public void setBz10(String bz10) {
        this.bz10 = bz10 == null ? null : bz10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz11
     *
     * @return the value of ehr.bz11
     *
     * @mbggenerated
     */
    public String getBz11() {
        return bz11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz11
     *
     * @param bz11 the value for ehr.bz11
     *
     * @mbggenerated
     */
    public void setBz11(String bz11) {
        this.bz11 = bz11 == null ? null : bz11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz12
     *
     * @return the value of ehr.bz12
     *
     * @mbggenerated
     */
    public String getBz12() {
        return bz12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz12
     *
     * @param bz12 the value for ehr.bz12
     *
     * @mbggenerated
     */
    public void setBz12(String bz12) {
        this.bz12 = bz12 == null ? null : bz12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz13
     *
     * @return the value of ehr.bz13
     *
     * @mbggenerated
     */
    public String getBz13() {
        return bz13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz13
     *
     * @param bz13 the value for ehr.bz13
     *
     * @mbggenerated
     */
    public void setBz13(String bz13) {
        this.bz13 = bz13 == null ? null : bz13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz14
     *
     * @return the value of ehr.bz14
     *
     * @mbggenerated
     */
    public String getBz14() {
        return bz14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz14
     *
     * @param bz14 the value for ehr.bz14
     *
     * @mbggenerated
     */
    public void setBz14(String bz14) {
        this.bz14 = bz14 == null ? null : bz14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz15
     *
     * @return the value of ehr.bz15
     *
     * @mbggenerated
     */
    public String getBz15() {
        return bz15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz15
     *
     * @param bz15 the value for ehr.bz15
     *
     * @mbggenerated
     */
    public void setBz15(String bz15) {
        this.bz15 = bz15 == null ? null : bz15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz16
     *
     * @return the value of ehr.bz16
     *
     * @mbggenerated
     */
    public String getBz16() {
        return bz16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz16
     *
     * @param bz16 the value for ehr.bz16
     *
     * @mbggenerated
     */
    public void setBz16(String bz16) {
        this.bz16 = bz16 == null ? null : bz16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz17
     *
     * @return the value of ehr.bz17
     *
     * @mbggenerated
     */
    public String getBz17() {
        return bz17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz17
     *
     * @param bz17 the value for ehr.bz17
     *
     * @mbggenerated
     */
    public void setBz17(String bz17) {
        this.bz17 = bz17 == null ? null : bz17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz18
     *
     * @return the value of ehr.bz18
     *
     * @mbggenerated
     */
    public String getBz18() {
        return bz18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz18
     *
     * @param bz18 the value for ehr.bz18
     *
     * @mbggenerated
     */
    public void setBz18(String bz18) {
        this.bz18 = bz18 == null ? null : bz18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz81
     *
     * @return the value of ehr.bz81
     *
     * @mbggenerated
     */
    public String getBz81() {
        return bz81;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz81
     *
     * @param bz81 the value for ehr.bz81
     *
     * @mbggenerated
     */
    public void setBz81(String bz81) {
        this.bz81 = bz81 == null ? null : bz81.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz82
     *
     * @return the value of ehr.bz82
     *
     * @mbggenerated
     */
    public String getBz82() {
        return bz82;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz82
     *
     * @param bz82 the value for ehr.bz82
     *
     * @mbggenerated
     */
    public void setBz82(String bz82) {
        this.bz82 = bz82 == null ? null : bz82.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz83
     *
     * @return the value of ehr.bz83
     *
     * @mbggenerated
     */
    public String getBz83() {
        return bz83;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz83
     *
     * @param bz83 the value for ehr.bz83
     *
     * @mbggenerated
     */
    public void setBz83(String bz83) {
        this.bz83 = bz83 == null ? null : bz83.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz84
     *
     * @return the value of ehr.bz84
     *
     * @mbggenerated
     */
    public String getBz84() {
        return bz84;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz84
     *
     * @param bz84 the value for ehr.bz84
     *
     * @mbggenerated
     */
    public void setBz84(String bz84) {
        this.bz84 = bz84 == null ? null : bz84.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz85
     *
     * @return the value of ehr.bz85
     *
     * @mbggenerated
     */
    public String getBz85() {
        return bz85;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz85
     *
     * @param bz85 the value for ehr.bz85
     *
     * @mbggenerated
     */
    public void setBz85(String bz85) {
        this.bz85 = bz85 == null ? null : bz85.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz102
     *
     * @return the value of ehr.bz102
     *
     * @mbggenerated
     */
    public String getBz102() {
        return bz102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz102
     *
     * @param bz102 the value for ehr.bz102
     *
     * @mbggenerated
     */
    public void setBz102(String bz102) {
        this.bz102 = bz102 == null ? null : bz102.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz103
     *
     * @return the value of ehr.bz103
     *
     * @mbggenerated
     */
    public String getBz103() {
        return bz103;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz103
     *
     * @param bz103 the value for ehr.bz103
     *
     * @mbggenerated
     */
    public void setBz103(String bz103) {
        this.bz103 = bz103 == null ? null : bz103.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz104
     *
     * @return the value of ehr.bz104
     *
     * @mbggenerated
     */
    public String getBz104() {
        return bz104;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz104
     *
     * @param bz104 the value for ehr.bz104
     *
     * @mbggenerated
     */
    public void setBz104(String bz104) {
        this.bz104 = bz104 == null ? null : bz104.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz105
     *
     * @return the value of ehr.bz105
     *
     * @mbggenerated
     */
    public String getBz105() {
        return bz105;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz105
     *
     * @param bz105 the value for ehr.bz105
     *
     * @mbggenerated
     */
    public void setBz105(String bz105) {
        this.bz105 = bz105 == null ? null : bz105.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz106
     *
     * @return the value of ehr.bz106
     *
     * @mbggenerated
     */
    public String getBz106() {
        return bz106;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz106
     *
     * @param bz106 the value for ehr.bz106
     *
     * @mbggenerated
     */
    public void setBz106(String bz106) {
        this.bz106 = bz106 == null ? null : bz106.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz107
     *
     * @return the value of ehr.bz107
     *
     * @mbggenerated
     */
    public String getBz107() {
        return bz107;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz107
     *
     * @param bz107 the value for ehr.bz107
     *
     * @mbggenerated
     */
    public void setBz107(String bz107) {
        this.bz107 = bz107 == null ? null : bz107.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz108
     *
     * @return the value of ehr.bz108
     *
     * @mbggenerated
     */
    public String getBz108() {
        return bz108;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz108
     *
     * @param bz108 the value for ehr.bz108
     *
     * @mbggenerated
     */
    public void setBz108(String bz108) {
        this.bz108 = bz108 == null ? null : bz108.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz109
     *
     * @return the value of ehr.bz109
     *
     * @mbggenerated
     */
    public String getBz109() {
        return bz109;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz109
     *
     * @param bz109 the value for ehr.bz109
     *
     * @mbggenerated
     */
    public void setBz109(String bz109) {
        this.bz109 = bz109 == null ? null : bz109.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz110
     *
     * @return the value of ehr.bz110
     *
     * @mbggenerated
     */
    public String getBz110() {
        return bz110;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz110
     *
     * @param bz110 the value for ehr.bz110
     *
     * @mbggenerated
     */
    public void setBz110(String bz110) {
        this.bz110 = bz110 == null ? null : bz110.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz111
     *
     * @return the value of ehr.bz111
     *
     * @mbggenerated
     */
    public String getBz111() {
        return bz111;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz111
     *
     * @param bz111 the value for ehr.bz111
     *
     * @mbggenerated
     */
    public void setBz111(String bz111) {
        this.bz111 = bz111 == null ? null : bz111.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz112
     *
     * @return the value of ehr.bz112
     *
     * @mbggenerated
     */
    public String getBz112() {
        return bz112;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz112
     *
     * @param bz112 the value for ehr.bz112
     *
     * @mbggenerated
     */
    public void setBz112(String bz112) {
        this.bz112 = bz112 == null ? null : bz112.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz113
     *
     * @return the value of ehr.bz113
     *
     * @mbggenerated
     */
    public String getBz113() {
        return bz113;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz113
     *
     * @param bz113 the value for ehr.bz113
     *
     * @mbggenerated
     */
    public void setBz113(String bz113) {
        this.bz113 = bz113 == null ? null : bz113.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz115
     *
     * @return the value of ehr.bz115
     *
     * @mbggenerated
     */
    public String getBz115() {
        return bz115;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz115
     *
     * @param bz115 the value for ehr.bz115
     *
     * @mbggenerated
     */
    public void setBz115(String bz115) {
        this.bz115 = bz115 == null ? null : bz115.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz116
     *
     * @return the value of ehr.bz116
     *
     * @mbggenerated
     */
    public String getBz116() {
        return bz116;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz116
     *
     * @param bz116 the value for ehr.bz116
     *
     * @mbggenerated
     */
    public void setBz116(String bz116) {
        this.bz116 = bz116 == null ? null : bz116.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz117
     *
     * @return the value of ehr.bz117
     *
     * @mbggenerated
     */
    public String getBz117() {
        return bz117;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz117
     *
     * @param bz117 the value for ehr.bz117
     *
     * @mbggenerated
     */
    public void setBz117(String bz117) {
        this.bz117 = bz117 == null ? null : bz117.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz118
     *
     * @return the value of ehr.bz118
     *
     * @mbggenerated
     */
    public String getBz118() {
        return bz118;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz118
     *
     * @param bz118 the value for ehr.bz118
     *
     * @mbggenerated
     */
    public void setBz118(String bz118) {
        this.bz118 = bz118 == null ? null : bz118.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz119
     *
     * @return the value of ehr.bz119
     *
     * @mbggenerated
     */
    public String getBz119() {
        return bz119;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz119
     *
     * @param bz119 the value for ehr.bz119
     *
     * @mbggenerated
     */
    public void setBz119(String bz119) {
        this.bz119 = bz119 == null ? null : bz119.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz120
     *
     * @return the value of ehr.bz120
     *
     * @mbggenerated
     */
    public String getBz120() {
        return bz120;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz120
     *
     * @param bz120 the value for ehr.bz120
     *
     * @mbggenerated
     */
    public void setBz120(String bz120) {
        this.bz120 = bz120 == null ? null : bz120.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz121
     *
     * @return the value of ehr.bz121
     *
     * @mbggenerated
     */
    public String getBz121() {
        return bz121;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz121
     *
     * @param bz121 the value for ehr.bz121
     *
     * @mbggenerated
     */
    public void setBz121(String bz121) {
        this.bz121 = bz121 == null ? null : bz121.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz128
     *
     * @return the value of ehr.bz128
     *
     * @mbggenerated
     */
    public String getBz128() {
        return bz128;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz128
     *
     * @param bz128 the value for ehr.bz128
     *
     * @mbggenerated
     */
    public void setBz128(String bz128) {
        this.bz128 = bz128 == null ? null : bz128.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz130
     *
     * @return the value of ehr.bz130
     *
     * @mbggenerated
     */
    public String getBz130() {
        return bz130;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz130
     *
     * @param bz130 the value for ehr.bz130
     *
     * @mbggenerated
     */
    public void setBz130(String bz130) {
        this.bz130 = bz130 == null ? null : bz130.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz131
     *
     * @return the value of ehr.bz131
     *
     * @mbggenerated
     */
    public String getBz131() {
        return bz131;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz131
     *
     * @param bz131 the value for ehr.bz131
     *
     * @mbggenerated
     */
    public void setBz131(String bz131) {
        this.bz131 = bz131 == null ? null : bz131.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz132
     *
     * @return the value of ehr.bz132
     *
     * @mbggenerated
     */
    public String getBz132() {
        return bz132;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz132
     *
     * @param bz132 the value for ehr.bz132
     *
     * @mbggenerated
     */
    public void setBz132(String bz132) {
        this.bz132 = bz132 == null ? null : bz132.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz134
     *
     * @return the value of ehr.bz134
     *
     * @mbggenerated
     */
    public String getBz134() {
        return bz134;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz134
     *
     * @param bz134 the value for ehr.bz134
     *
     * @mbggenerated
     */
    public void setBz134(String bz134) {
        this.bz134 = bz134 == null ? null : bz134.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz135
     *
     * @return the value of ehr.bz135
     *
     * @mbggenerated
     */
    public String getBz135() {
        return bz135;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz135
     *
     * @param bz135 the value for ehr.bz135
     *
     * @mbggenerated
     */
    public void setBz135(String bz135) {
        this.bz135 = bz135 == null ? null : bz135.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz136
     *
     * @return the value of ehr.bz136
     *
     * @mbggenerated
     */
    public String getBz136() {
        return bz136;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz136
     *
     * @param bz136 the value for ehr.bz136
     *
     * @mbggenerated
     */
    public void setBz136(String bz136) {
        this.bz136 = bz136 == null ? null : bz136.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz137
     *
     * @return the value of ehr.bz137
     *
     * @mbggenerated
     */
    public String getBz137() {
        return bz137;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz137
     *
     * @param bz137 the value for ehr.bz137
     *
     * @mbggenerated
     */
    public void setBz137(String bz137) {
        this.bz137 = bz137 == null ? null : bz137.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz139
     *
     * @return the value of ehr.bz139
     *
     * @mbggenerated
     */
    public String getBz139() {
        return bz139;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz139
     *
     * @param bz139 the value for ehr.bz139
     *
     * @mbggenerated
     */
    public void setBz139(String bz139) {
        this.bz139 = bz139 == null ? null : bz139.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz141
     *
     * @return the value of ehr.bz141
     *
     * @mbggenerated
     */
    public String getBz141() {
        return bz141;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz141
     *
     * @param bz141 the value for ehr.bz141
     *
     * @mbggenerated
     */
    public void setBz141(String bz141) {
        this.bz141 = bz141 == null ? null : bz141.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz142
     *
     * @return the value of ehr.bz142
     *
     * @mbggenerated
     */
    public String getBz142() {
        return bz142;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz142
     *
     * @param bz142 the value for ehr.bz142
     *
     * @mbggenerated
     */
    public void setBz142(String bz142) {
        this.bz142 = bz142 == null ? null : bz142.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz143
     *
     * @return the value of ehr.bz143
     *
     * @mbggenerated
     */
    public String getBz143() {
        return bz143;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz143
     *
     * @param bz143 the value for ehr.bz143
     *
     * @mbggenerated
     */
    public void setBz143(String bz143) {
        this.bz143 = bz143 == null ? null : bz143.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz144
     *
     * @return the value of ehr.bz144
     *
     * @mbggenerated
     */
    public String getBz144() {
        return bz144;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz144
     *
     * @param bz144 the value for ehr.bz144
     *
     * @mbggenerated
     */
    public void setBz144(String bz144) {
        this.bz144 = bz144 == null ? null : bz144.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz145
     *
     * @return the value of ehr.bz145
     *
     * @mbggenerated
     */
    public String getBz145() {
        return bz145;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz145
     *
     * @param bz145 the value for ehr.bz145
     *
     * @mbggenerated
     */
    public void setBz145(String bz145) {
        this.bz145 = bz145 == null ? null : bz145.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz146
     *
     * @return the value of ehr.bz146
     *
     * @mbggenerated
     */
    public String getBz146() {
        return bz146;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz146
     *
     * @param bz146 the value for ehr.bz146
     *
     * @mbggenerated
     */
    public void setBz146(String bz146) {
        this.bz146 = bz146 == null ? null : bz146.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz147
     *
     * @return the value of ehr.bz147
     *
     * @mbggenerated
     */
    public String getBz147() {
        return bz147;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz147
     *
     * @param bz147 the value for ehr.bz147
     *
     * @mbggenerated
     */
    public void setBz147(String bz147) {
        this.bz147 = bz147 == null ? null : bz147.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz149
     *
     * @return the value of ehr.bz149
     *
     * @mbggenerated
     */
    public String getBz149() {
        return bz149;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz149
     *
     * @param bz149 the value for ehr.bz149
     *
     * @mbggenerated
     */
    public void setBz149(String bz149) {
        this.bz149 = bz149 == null ? null : bz149.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz151
     *
     * @return the value of ehr.bz151
     *
     * @mbggenerated
     */
    public String getBz151() {
        return bz151;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz151
     *
     * @param bz151 the value for ehr.bz151
     *
     * @mbggenerated
     */
    public void setBz151(String bz151) {
        this.bz151 = bz151 == null ? null : bz151.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz152
     *
     * @return the value of ehr.bz152
     *
     * @mbggenerated
     */
    public String getBz152() {
        return bz152;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz152
     *
     * @param bz152 the value for ehr.bz152
     *
     * @mbggenerated
     */
    public void setBz152(String bz152) {
        this.bz152 = bz152 == null ? null : bz152.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz153
     *
     * @return the value of ehr.bz153
     *
     * @mbggenerated
     */
    public String getBz153() {
        return bz153;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz153
     *
     * @param bz153 the value for ehr.bz153
     *
     * @mbggenerated
     */
    public void setBz153(String bz153) {
        this.bz153 = bz153 == null ? null : bz153.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz154
     *
     * @return the value of ehr.bz154
     *
     * @mbggenerated
     */
    public String getBz154() {
        return bz154;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz154
     *
     * @param bz154 the value for ehr.bz154
     *
     * @mbggenerated
     */
    public void setBz154(String bz154) {
        this.bz154 = bz154 == null ? null : bz154.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz155
     *
     * @return the value of ehr.bz155
     *
     * @mbggenerated
     */
    public String getBz155() {
        return bz155;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz155
     *
     * @param bz155 the value for ehr.bz155
     *
     * @mbggenerated
     */
    public void setBz155(String bz155) {
        this.bz155 = bz155 == null ? null : bz155.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz157
     *
     * @return the value of ehr.bz157
     *
     * @mbggenerated
     */
    public String getBz157() {
        return bz157;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz157
     *
     * @param bz157 the value for ehr.bz157
     *
     * @mbggenerated
     */
    public void setBz157(String bz157) {
        this.bz157 = bz157 == null ? null : bz157.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz158
     *
     * @return the value of ehr.bz158
     *
     * @mbggenerated
     */
    public String getBz158() {
        return bz158;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz158
     *
     * @param bz158 the value for ehr.bz158
     *
     * @mbggenerated
     */
    public void setBz158(String bz158) {
        this.bz158 = bz158 == null ? null : bz158.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz159
     *
     * @return the value of ehr.bz159
     *
     * @mbggenerated
     */
    public String getBz159() {
        return bz159;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz159
     *
     * @param bz159 the value for ehr.bz159
     *
     * @mbggenerated
     */
    public void setBz159(String bz159) {
        this.bz159 = bz159 == null ? null : bz159.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz160
     *
     * @return the value of ehr.bz160
     *
     * @mbggenerated
     */
    public String getBz160() {
        return bz160;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz160
     *
     * @param bz160 the value for ehr.bz160
     *
     * @mbggenerated
     */
    public void setBz160(String bz160) {
        this.bz160 = bz160 == null ? null : bz160.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz162
     *
     * @return the value of ehr.bz162
     *
     * @mbggenerated
     */
    public String getBz162() {
        return bz162;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz162
     *
     * @param bz162 the value for ehr.bz162
     *
     * @mbggenerated
     */
    public void setBz162(String bz162) {
        this.bz162 = bz162 == null ? null : bz162.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz163
     *
     * @return the value of ehr.bz163
     *
     * @mbggenerated
     */
    public String getBz163() {
        return bz163;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz163
     *
     * @param bz163 the value for ehr.bz163
     *
     * @mbggenerated
     */
    public void setBz163(String bz163) {
        this.bz163 = bz163 == null ? null : bz163.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz165
     *
     * @return the value of ehr.bz165
     *
     * @mbggenerated
     */
    public String getBz165() {
        return bz165;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz165
     *
     * @param bz165 the value for ehr.bz165
     *
     * @mbggenerated
     */
    public void setBz165(String bz165) {
        this.bz165 = bz165 == null ? null : bz165.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz171
     *
     * @return the value of ehr.bz171
     *
     * @mbggenerated
     */
    public String getBz171() {
        return bz171;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz171
     *
     * @param bz171 the value for ehr.bz171
     *
     * @mbggenerated
     */
    public void setBz171(String bz171) {
        this.bz171 = bz171 == null ? null : bz171.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz172
     *
     * @return the value of ehr.bz172
     *
     * @mbggenerated
     */
    public String getBz172() {
        return bz172;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz172
     *
     * @param bz172 the value for ehr.bz172
     *
     * @mbggenerated
     */
    public void setBz172(String bz172) {
        this.bz172 = bz172 == null ? null : bz172.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz173
     *
     * @return the value of ehr.bz173
     *
     * @mbggenerated
     */
    public String getBz173() {
        return bz173;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz173
     *
     * @param bz173 the value for ehr.bz173
     *
     * @mbggenerated
     */
    public void setBz173(String bz173) {
        this.bz173 = bz173 == null ? null : bz173.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz174
     *
     * @return the value of ehr.bz174
     *
     * @mbggenerated
     */
    public String getBz174() {
        return bz174;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz174
     *
     * @param bz174 the value for ehr.bz174
     *
     * @mbggenerated
     */
    public void setBz174(String bz174) {
        this.bz174 = bz174 == null ? null : bz174.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz175
     *
     * @return the value of ehr.bz175
     *
     * @mbggenerated
     */
    public String getBz175() {
        return bz175;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz175
     *
     * @param bz175 the value for ehr.bz175
     *
     * @mbggenerated
     */
    public void setBz175(String bz175) {
        this.bz175 = bz175 == null ? null : bz175.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz204
     *
     * @return the value of ehr.bz204
     *
     * @mbggenerated
     */
    public String getBz204() {
        return bz204;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz204
     *
     * @param bz204 the value for ehr.bz204
     *
     * @mbggenerated
     */
    public void setBz204(String bz204) {
        this.bz204 = bz204 == null ? null : bz204.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz205
     *
     * @return the value of ehr.bz205
     *
     * @mbggenerated
     */
    public String getBz205() {
        return bz205;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz205
     *
     * @param bz205 the value for ehr.bz205
     *
     * @mbggenerated
     */
    public void setBz205(String bz205) {
        this.bz205 = bz205 == null ? null : bz205.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz206
     *
     * @return the value of ehr.bz206
     *
     * @mbggenerated
     */
    public String getBz206() {
        return bz206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz206
     *
     * @param bz206 the value for ehr.bz206
     *
     * @mbggenerated
     */
    public void setBz206(String bz206) {
        this.bz206 = bz206 == null ? null : bz206.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz268
     *
     * @return the value of ehr.bz268
     *
     * @mbggenerated
     */
    public String getBz268() {
        return bz268;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz268
     *
     * @param bz268 the value for ehr.bz268
     *
     * @mbggenerated
     */
    public void setBz268(String bz268) {
        this.bz268 = bz268 == null ? null : bz268.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz271
     *
     * @return the value of ehr.bz271
     *
     * @mbggenerated
     */
    public String getBz271() {
        return bz271;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz271
     *
     * @param bz271 the value for ehr.bz271
     *
     * @mbggenerated
     */
    public void setBz271(String bz271) {
        this.bz271 = bz271 == null ? null : bz271.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr.bz272
     *
     * @return the value of ehr.bz272
     *
     * @mbggenerated
     */
    public String getBz272() {
        return bz272;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr.bz272
     *
     * @param bz272 the value for ehr.bz272
     *
     * @mbggenerated
     */
    public void setBz272(String bz272) {
        this.bz272 = bz272 == null ? null : bz272.trim();
    }
}